#:schema node_modules/wrangler/config-schema.json

account_id = "9aad5614f4d224f93ac5d7a862223494"
name = "stripe-checkout"
main = "src/index.ts"

compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
name = "stripe-checkout"

[env.preview.vars]
name = "stripe-checkout-preview"

[observability]
enabled = true
