#:schema node_modules/wrangler/config-schema.json

account_id = "9aad5614f4d224f93ac5d7a862223494"
name = "stripe-checkout"
main = "src/index.ts"

compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]

CORS_ORIGIN = "http://localhost:5174"

[env.production.vars]
CORS_ORIGIN = "chrome-extension://eodajmolecppealblndaogcmkjaibfgb"
name = "stripe-checkout"

[env.preview.vars]
CORS_ORIGIN = "chrome-extension://ehoifpmjopfdbfhfedkpiiidngihgjlj"
name = "stripe-checkout-preview"

[observability]
enabled = true
