#:schema node_modules/wrangler/config-schema.json
name = "roast-free-usage-counter"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ROAST_FREE_USAGE_COUNTER"
id = "a80f180b9ad7453cbd6604c8774c778e"
