#:schema node_modules/wrangler/config-schema.json

account_id = "9aad5614f4d224f93ac5d7a862223494"
name = "stripe-customer-verification"
main = "src/index.ts"

compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]

CORS_ORIGIN = "chrome-extension://eodajmolecppealblndaogcmkjaibfgb"

[env.preview.vars]
CORS_ORIGIN = "chrome-extension://eodajmolecppealblndaogcmkjaibfgb"
name = "stripe-customer-verification-preview"

[observability]
enabled = true
