name: Deploy Stripe Checkout Worker (Production)

on:
  push:
    branches:
      - main
      - release/extension/0.1.0
    paths:
      - '.github/workflows/apps_stripe_checkout_publish_production.yml'
      - 'apps/stripe-checkout/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Preview
    defaults:
      run:
        working-directory: apps/stripe-checkout

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          workingDirectory: apps/stripe-checkout
          command: deploy